### ISSUE TITLE
registerElement code missing on Example 2

### ISSUE THREAD

**Issue by ArnoldHorshack** [stripe/elements-examples#23] opened 2017-11-28 21:19 UTC
I had a problem figuring out example 2 and got the missing code from Natalie on Stackoverflow  https://stackoverflow.com/questions/47540838/stripe-registerelement-not-defined

**Comment by jez** [comment] 2017-11-28 21:26
Duplicate of #22.

**Closed by jez** 2017-11-28 21:26 UTC
